module.exports = {
  name: "Digital Designers",
  title: "Digital Designers - Web Technology",
  description: "Innovating the Cloud Space while Embracing Humanity",
  keywords: [
    "Digital Designers",
    "Tech Community",
    "Jamstack Development",
    "Cloud Technology",
  ],
  url: "https://digitaldesigners.ca",
  language: "en",
  image: "/assets/social-image.jpg",
  rssUrl: "https://digitaldesigners.ca/rss.xml",
  feedUrl: "https://digitaldesigners.ca/feed.xml",
  feed: {
    subtitle: "Innovating the Cloud Space while Embracing Humanity",
    filename: "feed.xml",
    path: "/feed.xml",
    id: "https://digitaldesigners.ca",
  },
  jsonfeed: {
    path: "/feed.json",
    url: "https://digitaldesigners.ca/feed.json",
  },
  author: {
    name: "Kiri Vadivelu",
    email: "office@digitaldesigners.ca",
    jobTitle: "Jamstack Engineer",
    employer: "Digital Designers",
    city: "Toronto",
    country: "Canada",
    url: "https://digitaldesigners.ca",
    twitter: "https://twitter.com/kiri_vadivelu",
    facebook: "https://facebook.com/kiri.vadivelu",
    instagram: "https://instagram.com/kiri_vadivelu/",
    linkedin: "https://linkedin.com/in/kiri-vadivelu/",
  },
  Publisher: {
    name: "Digital Designers",
    city: "Toronto",
    country: "Canada",
    url: "https://digitaldesigners.ca",
    email: "hello@digitaldesigners.ca",
    logo: "https://digitaldesigners.ca/logo.png",
    twitter: "https://twitter.com/ddesignersca",
    facebook: "https://facebook.com/digitaldesignersca",
    instagram: "https://instagram.com/digitaldesignersca",
    linkedin: "https://linkedin.com/in/digitaldesignersca",
  },
  type: "website",
  local: "en_CA",
  city: "Toronto",
  country: "Canada",
  currentYear() {
    const today = new Date();
    return today.getFullYear();
  },
};
